type HighlightLanguage = { name: string; value: string };

const allLanguages: HighlightLanguage[] = [
    { name: '1C', value: '1c' },
    { name: 'ABNF', value: 'abnf' },
    { name: 'Access logs', value: 'accesslog' },
    { name: 'ActionScript', value: 'actionscript' },
    { name: 'Ada', value: 'ada' },
    { name: 'AngelScript', value: 'angelscript' },
    { name: 'Apache', value: 'apache' },
    { name: 'AppleScript', value: 'applescript' },
    { name: 'Arcade', value: 'arcade' },
    { name: 'Arduino (C++ w/Arduino libs)', value: 'arduino' },
    { name: 'ARM assembler', value: 'armasm' },
    { name: 'AsciiDoc', value: 'asciidoc' },
    { name: 'AspectJ', value: 'aspectj' },
    { name: 'AutoHotkey', value: 'autohotkey' },
    { name: 'AutoIt', value: 'autoit' },
    { name: 'AVR assembler', value: 'avrasm' },
    { name: 'Awk', value: 'awk' },
    { name: 'Bash', value: 'bash' },
    { name: 'BASIC', value: 'basic' },
    { name: 'BNF', value: 'bnf' },
    { name: 'Brainfuck', value: 'brainfuck' },
    { name: 'C', value: 'c' },
    { name: 'C#', value: 'csharp' },
    { name: 'C++', value: 'cpp' },
    { name: 'C/AL', value: 'cal' },
    { name: 'Cache Object Script', value: 'cos' },
    { name: 'Cap’n Proto', value: 'capnproto' },
    { name: 'Clojure', value: 'clojure' },
    { name: 'CMake', value: 'cmake' },
    { name: 'CoffeeScript', value: 'coffeescript' },
    { name: 'Coq', value: 'coq' },
    { name: 'Crmsh', value: 'crmsh' },
    { name: 'Crystal', value: 'crystal' },
    { name: 'CSP', value: 'csp' },
    { name: 'CSS', value: 'css' },
    { name: 'D', value: 'd' },
    { name: 'Dart', value: 'dart' },
    { name: 'Delphi', value: 'dpr' },
    { name: 'Diff', value: 'diff' },
    { name: 'Django', value: 'django' },
    { name: 'DNS Zone file', value: 'dns' },
    { name: 'Dockerfile', value: 'dockerfile' },
    { name: 'DOS', value: 'dos' },
    { name: 'dsconfig', value: 'dsconfig' },
    { name: 'DTS (Device Tree)', value: 'dts' },
    { name: 'Dust', value: 'dust' },
    { name: 'EBNF', value: 'ebnf' },
    { name: 'Elixir', value: 'elixir' },
    { name: 'Elm', value: 'elm' },
    { name: 'Erlang', value: 'erlang' },
    { name: 'Excel', value: 'excel' },
    { name: 'F#', value: 'fsharp' },
    { name: 'FIX', value: 'fix' },
    { name: 'Fortran', value: 'fortran' },
    { name: 'G-Code', value: 'gcode' },
    { name: 'Gams', value: 'gams' },
    { name: 'GAUSS', value: 'gauss' },
    { name: 'Gherkin', value: 'gherkin' },
    { name: 'Go', value: 'go' },
    { name: 'Golo', value: 'golo' },
    { name: 'Gradle', value: 'gradle' },
    { name: 'GraphQL', value: 'graphql' },
    { name: 'Groovy', value: 'groovy' },
    { name: 'Haml', value: 'haml' },
    { name: 'Handlebars', value: 'handlebars' },
    { name: 'Haskell', value: 'haskell' },
    { name: 'Haxe', value: 'haxe' },
    { name: 'HTML, XML', value: 'xml' },
    { name: 'HTTP', value: 'http' },
    { name: 'Hy', value: 'hy' },
    { name: 'Inform7', value: 'inform7' },
    { name: 'Ini, TOML', value: 'ini' },
    { name: 'IRPF90', value: 'irpf90' },
    { name: 'Java', value: 'java' },
    { name: 'JavaScript', value: 'javascript' },
    { name: 'JSON', value: 'json' },
    { name: 'Julia', value: 'julia' },
    { name: 'Julia REPL', value: 'julia-repl' },
    { name: 'Kotlin', value: 'kotlin' },
    { name: 'Lasso', value: 'lasso' },
    { name: 'LaTeX', value: 'tex' },
    { name: 'LDIF', value: 'ldif' },
    { name: 'Leaf', value: 'leaf' },
    { name: 'Less', value: 'less' },
    { name: 'Lisp', value: 'lisp' },
    { name: 'LiveCode Server', value: 'livecodeserver' },
    { name: 'LiveScript', value: 'livescript' },
    { name: 'Lua', value: 'lua' },
    { name: 'Makefile', value: 'makefile' },
    { name: 'Markdown', value: 'markdown' },
    { name: 'Mathematica', value: 'mathematica' },
    { name: 'Matlab', value: 'matlab' },
    { name: 'Maxima', value: 'maxima' },
    { name: 'Maya Embedded Language', value: 'mel' },
    { name: 'Mercury', value: 'mercury' },
    { name: 'MIPS Assembler', value: 'mips' },
    { name: 'Mizar', value: 'mizar' },
    { name: 'Mojolicious', value: 'mojolicious' },
    { name: 'Monkey', value: 'monkey' },
    { name: 'Moonscript', value: 'moonscript' },
    { name: 'N1QL', value: 'n1ql' },
    { name: 'Nginx', value: 'nginx' },
    { name: 'Nim', value: 'nim' },
    { name: 'Nix', value: 'nix' },
    { name: 'NSIS', value: 'nsis' },
    { name: 'Objective C', value: 'objectivec' },
    { name: 'OCaml', value: 'ocaml' },
    { name: 'OpenGL Shading Language', value: 'glsl' },
    { name: 'OpenSCAD', value: 'openscad' },
    { name: 'Oracle Rules Language', value: 'ruleslanguage' },
    { name: 'Oxygene', value: 'oxygene' },
    { name: 'Parser3', value: 'parser3' },
    { name: 'Perl', value: 'perl' },
    { name: 'PF', value: 'pf' },
    { name: 'PHP', value: 'php' },
    { name: 'Plaintext', value: 'plaintext' },
    { name: 'Pony', value: 'pony' },
    { name: 'PostgreSQL & PL/pgSQL', value: 'pgsql' },
    { name: 'PowerShell', value: 'powershell' },
    { name: 'Processing', value: 'processing' },
    { name: 'Prolog', value: 'prolog' },
    { name: 'Properties', value: 'properties' },
    { name: 'Protocol Buffers', value: 'proto' },
    { name: 'Puppet', value: 'puppet' },
    { name: 'Python', value: 'python' },
    { name: 'Python profiler results', value: 'profile' },
    { name: 'Python REPL', value: 'python-repl' },
    { name: 'Q', value: 'k' },
    { name: 'QML', value: 'qml' },
    { name: 'R', value: 'r' },
    { name: 'ReasonML', value: 'reasonml' },
    { name: 'RenderMan RIB', value: 'rib' },
    { name: 'RenderMan RSL', value: 'rsl' },
    { name: 'Roboconf', value: 'graph' },
    { name: 'Ruby', value: 'ruby' },
    { name: 'Rust', value: 'rust' },
    { name: 'SAS', value: 'SAS' },
    { name: 'Scala', value: 'scala' },
    { name: 'Scheme', value: 'scheme' },
    { name: 'Scilab', value: 'scilab' },
    { name: 'SCSS', value: 'scss' },
    { name: 'Shell', value: 'shell' },
    { name: 'Smali', value: 'smali' },
    { name: 'Smalltalk', value: 'smalltalk' },
    { name: 'SML', value: 'sml' },
    { name: 'SQL', value: 'sql' },
    { name: 'Stan', value: 'stan' },
    { name: 'Stata', value: 'stata' },
    { name: 'STEP Part 21', value: 'p21' },
    { name: 'Stylus', value: 'stylus' },
    { name: 'SubUnit', value: 'subunit' },
    { name: 'Swift', value: 'swift' },
    { name: 'Tcl', value: 'tcl' },
    { name: 'Test Anything Protocol', value: 'tap' },
    { name: 'Thrift', value: 'thrift' },
    { name: 'TP', value: 'tp' },
    { name: 'Twig', value: 'twig' },
    { name: 'TypeScript', value: 'typescript' },
    { name: 'Vala', value: 'vala' },
    { name: 'VB.Net', value: 'vbnet' },
    { name: 'VBScript', value: 'vbscript' },
    { name: 'Verilog', value: 'verilog' },
    { name: 'VHDL', value: 'vhdl' },
    { name: 'Vim Script', value: 'vim' },
    { name: 'X++', value: 'axapta' },
    { name: 'x86 Assembly', value: 'x86asm' },
    { name: 'XL', value: 'xl' },
    { name: 'XQuery', value: 'xquery' },
    { name: 'YAML', value: 'yml' },
    { name: 'Zephir', value: 'zephir' },
];

const popularOrder = [
    'python',
    'java',
    'go',
    'javascript',
    'cpp',
    'typescript',
    'php',
    'ruby',
    'c',
    'csharp',
    'nix',
    'shell',
    'rust',
    'scala',
    'kotlin',
    'swift',
    'dart',
    'groovy',
    'perl',
    'lua',
    'objectivec',
    'elixir',
    'ocaml',
    'haskell',
    'powershell',
    'erlang',
    'julia',
    'clojure',
    'r',
    'coffeescript',
    'fsharp',
    'verilog',
    'fortran',
    'matlab',
    'puppet',
    'scss',
    'smalltalk',
    'vala',
    'haxe',
    'dpr',
];

const popularLanguages = popularOrder
    .map((value) => allLanguages.find((language) => language.value === value))
    .filter((language): language is HighlightLanguage => Boolean(language));

const popularSet = new Set(popularLanguages.map((language) => language.value));

const remainingLanguages = allLanguages
    .filter((language) => !popularSet.has(language.value))
    .sort((a, b) => a.name.localeCompare(b.name));

export const highlightLanguages = [...popularLanguages, ...remainingLanguages];
