type HighlightLanguage = { name: string; value: string };

export const allLanguages: HighlightLanguage[] = [
    { name: 'Python', value: 'python' },
    { name: 'C', value: 'c' },
    { name: 'C++', value: 'cpp' },
    { name: 'Java', value: 'java' },
    { name: 'C#', value: 'csharp' },
    { name: 'JavaScript', value: 'javascript' },
    { name: 'TypeScript', value: 'typescript' },
    { name: 'CSS', value: 'css' },
    { name: 'HTML / XML', value: 'xml' },
    { name: 'SQL', value: 'sql' },
    { name: 'Go', value: 'go' },
    { name: 'Rust', value: 'rust' },
    { name: 'MATLAB', value: 'matlab' },
    { name: 'R', value: 'r' },
    { name: 'PHP', value: 'php' },
    { name: 'Swift', value: 'swift' },
    { name: 'Kotlin', value: 'kotlin' },
    { name: 'Scala', value: 'scala' },
    { name: 'Visual Basic / VB.Net', value: 'vbnet' },
    { name: 'Assembly (MIPS)', value: 'mips' },
    { name: 'Groovy', value: 'groovy' },
    { name: 'Ruby', value: 'ruby' },
    { name: 'Objective C', value: 'objectivec' },
    { name: 'Dart', value: 'dart' },
    { name: 'Julia', value: 'julia' },
    { name: 'Haskell', value: 'haskell' },
    { name: 'Elixir', value: 'elixir' },
    { name: 'PowerShell', value: 'powershell' },
    { name: 'Shell', value: 'shell' },
    { name: 'Perl', value: 'perl' },
    { name: 'Clojure', value: 'clojure' },
    { name: 'F#', value: 'fsharp' },
    { name: 'Scheme', value: 'scheme' },
    { name: 'Tcl', value: 'tcl' },

    { name: 'YAML', value: 'yml' },
    { name: 'INI', value: 'ini' },
    { name: 'Dockerfile', value: 'dockerfile' },
    { name: 'GraphQL', value: 'graphql' },
    { name: 'Handlebars', value: 'handlebars' },
    { name: 'LESS', value: 'less' },
    { name: 'SCSS', value: 'scss' },
    { name: 'Twig', value: 'twig' },
    { name: 'Protobuf', value: 'proto' },
    { name: 'Markdown', value: 'markdown' },
    { name: 'PostgreSQL', value: 'pgsql' },
    { name: 'CSP', value: 'csp' },
];

export const highlightLanguages = allLanguages.map((lang) => lang.value);